FROM node:11.10.1-alpine
RUN apk add --no-cache bash git openssh

WORKDIR /opt/app

COPY package.json yarn.lock ./
RUN yarn install --production=true --frozen-lockfile

COPY . ./
RUN yarn preview:build

EXPOSE 80
CMD ["yarn", "preview:start"]
