# name: E2E visual testing

# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# on:
#   push:
#     branches-ignore:
#       - master

# jobs:
#   wait_for_vercel:
#     name: Wait for vercel
#     runs-on: ubuntu-latest
#     outputs:
#       preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
#     steps:
#       - name: Wait for Vercel preview deployment to be ready
#         uses: patrickedqvist/wait-for-vercel-preview@main
#         id: waitForVercelPreviewDeployment
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           max_timeout: 120

#   tests:
#     name: End-to-end tests
#     needs: wait_for_vercel
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Vercel steps.dep
#         run: echo "${{steps.deployment-url.outputs.url}}"

#       - name: Vercel CLI
#         run: |-
#           echo "Test status:${{steps.plan.outcome}}" >> $GITHUB_STEP_SUMMARY

#       - name: Percy
#         run: npx @percy/cli snapshot snapshots.js
#         env:
#           VERCEL_URL: ${{ needs.wait_for_vercel.outputs.preview_url }}
#           VERCEL_ENV: preview
#           PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
